# This workflow will build a docker container, publish it to IBM Container Registry, and deploy it to IKS when there is a push to the "main" branch.
#
# To configure this workflow:
#
# 1. Ensure that your repository contains a Dockerfile
# 2. Setup secrets in your repository by going to settings: Create ICR_NAMESPACE and IBM_CLOUD_API_KEY



name: Build and Deploy to IBM Code engine

on:
  push:
    branches: [ "main" , "test" ]

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    # Download and Install IBM Cloud CLI
    - name: Install IBM Cloud CLI
      run: |
        curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
        ibmcloud --version
        ibmcloud config --check-version=false
        ibmcloud plugin install -f container-registry
        ibmcloud plugin install -f code-engine

    # Authenticate with IBM Cloud CLI
    - name: Authenticate with IBM Cloud CLI
      run: |
        ibmcloud login --apikey "Y-HEauco3N7zFroAUtDGNRMIC0ngcmCDCB-erAOZDChm" -r "us-south" -g Pruebas-Huemul
        ibmcloud cr region-set "us-south"
        ibmcloud cr project select --name Code Engine Huemul-FID
        ibmcloud cr login

    # Build the Docker image
    - name: Build Docker image
      run: |
        
        docker build -t us.icr.io/huemulnamespace/code-engine:${{ github.sha }} .
        
    
    # Push the image to IBM Container Registry
    - name: Push the image to ICR
      run: |
          docker push us.icr.io/huemulnamespace/code-engine:${{ github.sha }}

    - name: Update in IBM Cloud Code Engine
      run: |
        ibmcloud ce app update --name demo-seba1-hello-world --image /huemulnamespace/code-engine:${{ github.sha }}:latest 


    #- name: Checkout código
    #  uses: actions/checkout@v2
    #- name: Actualizar en Code Engine
    #  uses: actions/checkout@v2
    #    with:
    #      CE_PROJECT_NAME: Code Engine Huemul-FID
    #      CE_APP_NAME: epysa-2
    #      IMAGE: code-engine:${{ github.sha }}:latest
    #      CE_ACTION: update
        
    
